### ISSUE TITLE
Provider Ports

### ISSUE THREAD

**Issue by BannanaDJoe** [vciancio/golem-dashboard#9]
Hello how you get the Provider Ports i tryed anything that isn´t working. Any idea or suggestion ?

**Comment by vciancio** [comment]
Sorry, to not sure what you mean specifically by 'get the Provider Ports'. Do you mean view it in the UI or when setting up the config?

By default, the ports for the [provider](https://github.com/vciancio/golem-node-server#setup---servergolemyanga) will default to `5000` unless you've changed it. So when you run the dashboard, you can via 
~~~ bash
REACT_APP_ADDRESSES=192.168.1.2:5000 npm start
~~~
or with docker via 
~~~ bash
docker run -e REACT_APP_ADDRESSES=192.168.1.2:5000 -p 3000:3000 vciancio/golem-dashboard
~~~

Does that answer your question?

**Comment by BannanaDJoe** [comment]
Right if i run it like your discription with port 5000 for the Provider this dosent work. i hasn´t changed the ports or anything this is a default installed Provider with the newest yagna verison. 
![image](https://user-images.githubusercontent.com/35501852/120210212-d18f1a00-c22f-11eb-9b1c-41d7632d7df7.png)

if i check the running ports on the system with netstat -pantule there isn´t a 5000 port.

**Comment by vciancio** [comment]
Just to confirm, you're running the container/flask server that I mentioned in my last comment, right? https://github.com/vciancio/golem-node-server

**Comment by BannanaDJoe** [comment]
right. im running your container and the golem provider on a ubuntu device

**Comment by vciancio** [comment]
> right. im running your container and the golem provider on a ubuntu device 

Hmm.

What command are you using to run the container?

Also you said that your running the container and the golem provider on the node. By container you mean this one, there node-server, right? Want to make sure you're not running both this container and a separate golem provider on the same machine.

**Comment by BannanaDJoe** [comment]
i run it with docker-compose up -d 

Golem Provider and Golem-Dashboard are two different VM´s 

i really dont understand how you can connect to port 5000 ( golem Provider ). 

Your Golem-Dashboard start well but i cant connect to the golem Provider. That is the main issue.

**Comment by BannanaDJoe** [comment]
.
